/* Generated By:JavaCC: Do not edit this line. ArbolTreeConstants.java Version 5.0 */
package Aritmetica;

public interface ArbolTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTSTATEMENT = 2;
  public int JJTVARIABLE = 3;
  public int JJTADDEXPR = 4;
  public int JJTSUBRACTEXPR = 5;
  public int JJTMULTIPLYEXPR = 6;
  public int JJTDIVIDEEXPR = 7;
  public int JJTNEGATEEXPR = 8;
  public int JJTNUMBER = 9;
  public int JJTVARIABLEVALUE = 10;


  public String[] jjtNodeName = {
    "start",
    "void",
    "Statement",
    "Variable",
    "AddExpr",
    "SubractExpr",
    "MultiplyExpr",
    "DivideExpr",
    "NegateExpr",
    "Number",
    "VariableValue",
  };
}
/* JavaCC - OriginalChecksum=054b723d402ffe5d847a15e576f99896 (do not edit this line) */
