/* Generated By:JavaCC: Do not edit this line. ArbolVisitor.java Version 5.0 */
package Aritmetica;

public interface ArbolVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTstart node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTVariable node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTSubractExpr node, Object data);
  public Object visit(ASTMultiplyExpr node, Object data);
  public Object visit(ASTDivideExpr node, Object data);
  public Object visit(ASTNegateExpr node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTVariableValue node, Object data);
}
/* JavaCC - OriginalChecksum=4b9acd9ebf4c649dbfb5a231e0bab232 (do not edit this line) */
