/* Generated By:JJTree: Do not edit this line. ASTMultiplyExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Aritmetica;

public
class ASTMultiplyExpr extends SimpleNode {
  public ASTMultiplyExpr(int id) {
    super(id);
  }

  public ASTMultiplyExpr(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=84d70b2b579055b27c386fbacec5e3ee (do not edit this line) */
