/* Generated By:JJTree: Do not edit this line. ASTNegateExpr.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Aritmetica;

public
class ASTNegateExpr extends SimpleNode {
  public ASTNegateExpr(int id) {
    super(id);
  }

  public ASTNegateExpr(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=f6b3bb38ddc627d0fc97c49aeb6395e0 (do not edit this line) */
