/* Generated By:JJTree: Do not edit this line. ASTstart.java Version 4.3 */
/* JavaCCOptions:MULTI=true,NODE_USES_PARSER=false,VISITOR=true,TRACK_TOKENS=false,NODE_PREFIX=AST,NODE_EXTENDS=BaseNode,NODE_FACTORY=,SUPPORT_CLASS_VISIBILITY_PUBLIC=true */
package Aritmetica;

public
class ASTstart extends SimpleNode {
  public ASTstart(int id) {
    super(id);
  }

  public ASTstart(ExpressionParser p, int id) {
    super(p, id);
  }


  /** Accept the visitor. **/
  public Object jjtAccept(ExpressionParserVisitor visitor, Object data) {
    return visitor.visit(this, data);
  }
}
/* JavaCC - OriginalChecksum=859a1b97e7d5e27c169c33424f44abef (do not edit this line) */
