/* Generated By:JavaCC: Do not edit this line. ExpressionParserTreeConstants.java Version 5.0 */
package Aritmetica;

public interface ExpressionParserTreeConstants
{
  public int JJTSTART = 0;
  public int JJTVOID = 1;
  public int JJTSTATEMENT = 2;
  public int JJTADDEXPR = 3;
  public int JJTSUBRACTEXPR = 4;
  public int JJTMULTIPLYEXPR = 5;
  public int JJTDIVIDEEXPR = 6;
  public int JJTNEGATEEXPR = 7;
  public int JJTNUMBER = 8;
  public int JJTVARIABLE = 9;


  public String[] jjtNodeName = {
    "start",
    "void",
    "Statement",
    "AddExpr",
    "SubractExpr",
    "MultiplyExpr",
    "DivideExpr",
    "NegateExpr",
    "Number",
    "Variable",
  };
}
/* JavaCC - OriginalChecksum=aca91d2ec575497787dc57c8f79cd271 (do not edit this line) */
