/* Generated By:JavaCC: Do not edit this line. ExpressionParserVisitor.java Version 5.0 */
package Aritmetica;

public interface ExpressionParserVisitor
{
  public Object visit(SimpleNode node, Object data);
  public Object visit(ASTstart node, Object data);
  public Object visit(ASTStatement node, Object data);
  public Object visit(ASTAddExpr node, Object data);
  public Object visit(ASTSubractExpr node, Object data);
  public Object visit(ASTMultiplyExpr node, Object data);
  public Object visit(ASTDivideExpr node, Object data);
  public Object visit(ASTNegateExpr node, Object data);
  public Object visit(ASTNumber node, Object data);
  public Object visit(ASTVariable node, Object data);
}
/* JavaCC - OriginalChecksum=4eb9227f6647eced861356f94ad76f37 (do not edit this line) */
